import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

// Root é client/ e o build vai para client/dist
// Base /wellness/ garante que os assets sejam servidos corretamente no HostGator

export default defineConfig({
  root: path.resolve(__dirname, 'client'),
  base: '/wellness/',
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'client/src'),
      '@lib': path.resolve(__dirname, 'client/src/lib'),
      '@shims': path.resolve(__dirname, 'client/src/lib/shims'),
      '@shared': path.resolve(__dirname, 'shared'),
      '@tanstack/react-query': path.resolve(__dirname, 'client/src/lib/shims/react-query.ts'),
      '@trpc/client': path.resolve(__dirname, 'client/src/lib/shims/trpc.ts'),
      'wouter': path.resolve(__dirname, 'client/src/lib/shims/wouter.ts'),
      'superjson': path.resolve(__dirname, 'client/src/lib/shims/superjson.ts'),
      'i18next': path.resolve(__dirname, 'client/src/lib/shims/i18next.ts'),
      'react-i18next': path.resolve(__dirname, 'client/src/lib/shims/react-i18next.ts'),
      'lucide-react': path.resolve(__dirname, 'client/src/lib/shims/lucide-react.ts'),
      'sonner': path.resolve(__dirname, 'client/src/lib/shims/sonner.ts'),
      'clsx': path.resolve(__dirname, 'client/src/lib/shims/clsx.ts'),
      'tailwind-merge': path.resolve(__dirname, 'client/src/lib/shims/tailwind-merge.ts'),
      'class-variance-authority': path.resolve(__dirname, 'client/src/lib/shims/class-variance-authority.ts'),
      'next-themes': path.resolve(__dirname, 'client/src/lib/shims/next-themes.ts'),
      'date-fns/locale': path.resolve(__dirname, 'client/src/lib/shims/date-fns-locale.ts'),
      'date-fns': path.resolve(__dirname, 'client/src/lib/shims/date-fns.ts'),
      'react-day-picker': path.resolve(__dirname, 'client/src/lib/shims/react-day-picker.ts'),
      'recharts': path.resolve(__dirname, 'client/src/lib/shims/recharts.ts'),
      'cmdk': path.resolve(__dirname, 'client/src/lib/shims/cmdk.ts'),
      'vaul': path.resolve(__dirname, 'client/src/lib/shims/vaul.ts'),
      'streamdown': path.resolve(__dirname, 'client/src/lib/shims/streamdown.ts'),
      'input-otp': path.resolve(__dirname, 'client/src/lib/shims/input-otp.ts'),
      'react-resizable-panels': path.resolve(__dirname, 'client/src/lib/shims/react-resizable-panels.ts'),
      '@radix-ui/react-accordion': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-accordion.ts'),
      '@radix-ui/react-alert-dialog': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-alert-dialog.ts'),
      '@radix-ui/react-aspect-ratio': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-aspect-ratio.ts'),
      '@radix-ui/react-avatar': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-avatar.ts'),
      '@radix-ui/react-checkbox': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-checkbox.ts'),
      '@radix-ui/react-collapsible': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-collapsible.ts'),
      '@radix-ui/react-context-menu': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-context-menu.ts'),
      '@radix-ui/react-dialog': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-dialog.ts'),
      '@radix-ui/react-dropdown-menu': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-dropdown-menu.ts'),
      '@radix-ui/react-hover-card': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-hover-card.ts'),
      '@radix-ui/react-label': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-label.ts'),
      '@radix-ui/react-menubar': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-menubar.ts'),
      '@radix-ui/react-navigation-menu': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-navigation-menu.ts'),
      '@radix-ui/react-popover': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-popover.ts'),
      '@radix-ui/react-progress': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-progress.ts'),
      '@radix-ui/react-radio-group': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-radio-group.ts'),
      '@radix-ui/react-scroll-area': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-scroll-area.ts'),
      '@radix-ui/react-select': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-select.ts'),
      '@radix-ui/react-separator': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-separator.ts'),
      '@radix-ui/react-slider': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-slider.ts'),
      '@radix-ui/react-slot': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-slot.ts'),
      '@radix-ui/react-switch': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-switch.ts'),
      '@radix-ui/react-tabs': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-tabs.ts'),
      '@radix-ui/react-toggle': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-toggle.ts'),
      '@radix-ui/react-toggle-group': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-toggle-group.ts'),
      '@radix-ui/react-tooltip': path.resolve(__dirname, 'client/src/lib/shims/radix-ui-react-tooltip.ts'),
      'zustand/middleware': path.resolve(__dirname, 'client/src/lib/shims/zustand-middleware.ts'),
      'zustand': path.resolve(__dirname, 'client/src/lib/shims/zustand.ts'),
    },
  },

  build: {
    outDir: path.resolve(__dirname, 'client/dist'),
    emptyOutDir: true,
  },
});
